# Generated by Django 4.1.5 on 2023-01-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_room_host_room_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
    ]
