# Generated by Django 4.1.5 on 2023-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_room_host_remove_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
